//@version=6
indicator("polyline width 151 trace v17 v1",overlay=false,precision=16)
if barstate.islast
    control=array.from(chart.point.from_index(bar_index-40,2),chart.point.from_index(bar_index-3,2))
    target=array.from(chart.point.from_index(bar_index-40,8),chart.point.from_index(bar_index-3,8))
    polyline.new(control,line_width=100,line_color=color.blue)
    polyline.new(target,line_width=151,line_color=color.red)
plot(0,"SCALE_MIN",color=color.new(color.gray,100))
plot(10,"SCALE_MAX",color=color.new(color.gray,100))
plot(bar_index,"INPUT_BAR_INDEX",display=display.data_window)
plot(151,"REQUESTED_WIDTH",display=display.data_window)
plot(barstate.islast?1:na,"CREATION_REACHED",display=display.data_window)
