//@version=6
indicator("box width 151 trace v17 v1",overlay=false,precision=16)
if barstate.islast
    box.new(bar_index-40,8,bar_index-25,2,border_width=100,border_color=color.blue,bgcolor=na)
    box.new(bar_index-18,8,bar_index-3,2,border_width=151,border_color=color.red,bgcolor=na)
plot(0,"SCALE_MIN",color=color.new(color.gray,100))
plot(10,"SCALE_MAX",color=color.new(color.gray,100))
plot(bar_index,"INPUT_BAR_INDEX",display=display.data_window)
plot(151,"REQUESTED_WIDTH",display=display.data_window)
plot(barstate.islast?1:na,"CREATION_REACHED",display=display.data_window)
