//@version=6
indicator("V13 polyline curved native path", max_polylines_count=2)
if barstate.islastconfirmedhistory
    points = array.from(chart.point.from_index(bar_index-8,1), chart.point.from_index(bar_index-6,4), chart.point.from_index(bar_index-3,-2), chart.point.from_index(bar_index,2))
    polyline.new(points,curved=true,line_color=color.red,line_width=3)
    polyline.new(points,curved=false,line_color=color.blue,line_width=1)
plot(na)
