//@version=3
study("V13 plotarrow offset v3 zero-control",overlay=true)
phase=n%32
source=phase==8?1:phase==9?-1:phase==11?4:phase==12?-4:0
series_offset=phase<10?2:phase<12?-1:-3
plotarrow(source,colorup=lime,colordown=red,offset=0,minheight=10,maxheight=50)
plot(n,"BAR_INDEX",transp=100)
plot(source,"SOURCE",transp=100)
plot(0,"OFFSET",transp=100)
plot(10,"MINHEIGHT",transp=100)
plot(50,"MAXHEIGHT",transp=100)
