//@version=5
indicator("Namespace methods")
import sours-lat/R2Nsdba23857d1c2/1 as lib
outer(value) => request.security("BINANCE:BTCUSDT", "1D", request.security("BINANCE:BTCUSDT", "1D", lib.pick(value) + lib.pick(int(7)), lookahead=barmerge.lookahead_on), lookahead=barmerge.lookahead_on)
plot(outer(close))
plot(request.security("BINANCE:BTCUSDT", "1D", close, lookahead=barmerge.lookahead_on), title="REQUESTED_CLOSE_CONTROL")
