//@version=6
indicator("trace-array-nearest-rank-float-boundaries-control-v6")
a = array.from(10.5, 20.5, 30.5, 40.5, 50.5)
percentage = bar_index % 3 == 0 ? 0.0 : bar_index % 3 == 1 ? 50.0 : 100.0
result = array.percentile_nearest_rank(a, percentage)
plot(bar_index, "BAR_INDEX", display=display.data_window)
plot(percentage, "PERCENTAGE", display=display.data_window)
plot(result, "OUTCOME", display=display.data_window)
