//@version=6
indicator("BE independent specialization")
float unused = array.get(array.from(1.0), timeframe.isdaily ? 1 : 0)
method sample(int self) => unused
method sample(float self) => self
inner(value) => request.security(syminfo.tickerid,"1D",value.sample(),lookahead=barmerge.lookahead_on)
outer(value) => request.security(syminfo.tickerid,"1D",inner(value),lookahead=barmerge.lookahead_on)
plot(outer(close))