//@version=6
indicator("V33 isolated component")
v33_close = switch bar_index
    0 => 10.0
    1 => 11.0
    2 => 9.0
    3 => 13.0
    4 => 8.0
    5 => 15.0
    => float(na)
plot(v33_close, "SRC_CLOSE")
v33_high = switch bar_index
    0 => 12.0
    1 => 14.0
    2 => 13.0
    3 => 16.0
    4 => 15.0
    5 => 18.0
    => float(na)
plot(v33_high, "SRC_HIGH")
v33_low = switch bar_index
    0 => 8.0
    1 => 9.0
    2 => 7.0
    3 => 10.0
    4 => 6.0
    5 => 12.0
    => float(na)
plot(v33_low, "SRC_LOW")
plot(bar_index, "INDEX")
plot(ta.mfi(((v33_high + v33_low + v33_close) / 3), 3), "VALUE_1")
