//@version=6
indicator("V33 isolated component")
v33_high = switch bar_index
    0 => 1.0
    1 => -1.0
    2 => 1.0
    3 => 3.0
    4 => 0.0
    5 => 4.0
    6 => 1.0
    7 => -2.0
    8 => 2.0
    9 => 1.0
    10 => -1.0
    11 => 3.0
    => float(na)
plot(v33_high, "SRC_HIGH")
v33_low = switch bar_index
    0 => -1.0
    1 => -3.0
    2 => -1.0
    3 => 1.0
    4 => -2.0
    5 => 2.0
    6 => -1.0
    7 => -4.0
    8 => 0.0
    9 => -1.0
    10 => -3.0
    11 => 1.0
    => float(na)
plot(v33_low, "SRC_LOW")
v33_close = switch bar_index
    0 => 0.0
    1 => -2.0
    2 => 0.0
    3 => 2.0
    4 => -1.0
    5 => 3.0
    6 => 0.0
    7 => -3.0
    8 => 1.0
    9 => 0.0
    10 => -2.0
    11 => 2.0
    => float(na)
plot(v33_close, "SRC_CLOSE")
plot(bar_index, "INDEX")
plot(ta.sma(v33_close, 3)[1], "VALUE_1")
plot(ta.ema(v33_close, 3)[1], "VALUE_2")
plot(ta.atr(3)[1], "VALUE_3")
plot(ta.highest(v33_high, 3)[1], "VALUE_4")
plot(ta.lowest(v33_low, 3)[1], "VALUE_5")
plot(ta.crossover(v33_close, 0)[1] ? 1 : 0, "VALUE_6")
plot(ta.crossunder(v33_close, 0)[1] ? 1 : 0, "VALUE_7")
plot(ta.rsi(v33_close, 3)[1], "VALUE_8")
plot(ta.rma(v33_close, 3)[1], "VALUE_9")
plot(ta.wma(v33_close, 3)[1], "VALUE_10")
plot(ta.barssince(v33_close > 0)[1], "VALUE_11")
plot(ta.tr(true)[1], "VALUE_12")
