//@version=6
indicator("Round input with simple precision")
simple int precision = int(syminfo.mintick) > 0 ? 1 : 2
number = input.float(2.125, "Number")
positional = math.round(number, precision)
named = math.round(precision=precision, number=number)
plot(precision, title="Simple_precision")
plot(positional, title="Input_positional")
plot(named, title="Input_named")
plot(close, title="Input_linewidth_consumer", linewidth=int(positional))
