//@version=6
indicator("Unsupported array.abs SameAsArg return qualifier")

ints = array.from(-1, 2, -3)
floats = array.from(-1.0, 2.0, -3.0)
int_matrix = matrix.new<int>(1, 3, 0)
float_matrix = matrix.new<float>(1, 3, 0.0)

matrix.add_row(float_matrix, 0, array.abs(ints))
matrix.add_col(int_matrix, 0, floats.abs())
matrix.add_row(int_matrix, 0, array.abs(floats))
matrix.add_col(float_matrix, 0, ints.abs())
