//@version=6
indicator("V52 qualifier-match-input-regex-simple", calc_bars_count=32)
sourceText = "abXab"
regexText = input.string("[a-z]+", "Regex")
value = str.match(source=sourceText, regex=regexText)
consume(simple string sampleText) => str.length(sampleText)
plot(consume(value), "CONSUMER")
plot(str.length(value), "TARGET_LENGTH")
plot(value == "ab" ? 1 : 0, "TARGET_EQUAL")
plot(na(value) ? 1 : 0, "TARGET_NA")
if barstate.isfirst
    log.info("TARGET=[{0}]", value)
plot(bar_index, "INDEX")
plot(close, "CONTROL_CLOSE")
